dist: trusty
sudo: required

addons:
#  chrome: stable
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
  #sourceclear addons, take care it requires fees
  #srcclr: true
#  apt:
#    packages:
#      - nginx
#      - php-fpm

env:
  global:
    - SERVER_HOST_WEB="localhost:80"

language: php
php:
  - 7.1

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo add-apt-repository -y ppa:ondrej/nginx-mainline
  - sudo apt-get update
  - sudo apt-get install nginx
#  - sudo apt-get install php7.1-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp var/travis/nginx.conf /etc/nginx/sites-available/$SERVER_HOST_WEB.conf
  - sudo ln -s /etc/nginx/sites-available/$SERVER_HOST_WEB /etc/nginx/sites-enabled/
  - nvm install 8.9.0
  - nvm use 8.9.0
# see http://devexpress.github.io/testcafe/documentation/recipes/integrating-testcafe-with-ci-systems/travis.html
  - stty cols 80

install:
  - npm run init-project
  - npm run jwt-generation-test

before_script:
#  - curl -H "Accept: application/json" https://security.sensiolabs.org/check_lock -F lock=@composer.lock
#  - sudo service php7.1-fpm restart
  - sudo service nginx restart
# see http://devexpress.github.io/testcafe/documentation/recipes/integrating-testcafe-with-ci-systems/travis.html
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

script:
# until this issue is open i disable npm test and use test-php and test-karma in place (issue:https://github.com/DevExpress/testcafe/issues/2195, original post: https://testcafe-discuss.devexpress.com/t/role-sometime-it-doesnt-seem-to-be-played/875/9)
#  - npm test
  - npm run test-php
  - npm run test-karma

notifications:
  email: false