index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

simple:
    path: /demo/simple
    defaults: { _controller: 'App\Controller\SimpleController::index' }
    methods:
        - "GET"

# SECURITY
# firewall JSON: do not uncomment ! if you do and replace the path in the security.yaml by the name of the route, it will fail !
# @todo: open an issue on Symfony to see if the behaviour is 'expected'
#demo_login_json_check:
#    path: /demo/login/json
demo_login_json_logout:
    path: /demo/login/json/logout
# firewall MAIN
demo_login_standard_check:
    # take care : the route must be behind your firewall : in main section we have to add this route to the pattern node
    path: /demo/login/authenticate
demo_login_standard_logout:
    path: /demo/login/logout
